name: Upgrade Backstage

on:
  schedule:
    - cron: '0 1 1 * *' # 1 am UTC on 1st day of every month
  workflow_dispatch: {}

jobs:
  upgrade:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Upgrade plugins
        run: |
          yarn install
          yarn backstage-cli versions:bump
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git checkout -b deps/upgrade-backstage
          git diff-index --quiet HEAD || git commit -m "chore(deps): Upgrade Backstage versions"
      - name: Test changes
        run: |
          yarn install
          yarn ci
        env:
          CI: true
        continue-on-error: true

      - name: Push changes
        run: |
          git push -o merge_request.create -o merge_request.draft \
          -o merge_request.target=main -o merge_request.title="Upgrade Backstage versions" \
          -o merge_request.description="Upgrade Backstage dependencies" -u origin deps/upgrade-backstage